### ISSUE TITLE
【问题】号池管理添加多个账号保存不生效； 

### ISSUE THREAD

**Issue by wstanfeng** [Chenyme/oaifree-tools#3]
号池管理添加多个账号保存不生效； docker能否加添对arm的支持呢？

**Comment by Chenyme** [comment]
感谢反馈！
需要注意的是，号池管理时**用户组**是每个账号的唯一标识，不允许命名相同。
会考虑支持的

**Comment by chenyme** [comment]
This post is too long and will be closed automatically
