### ISSUE TITLE
Fucluade退出登录跳转回原登录页面

### ISSUE THREAD

**Issue by xianyu110** [Chenyme/oaifree-tools#4]
Fucluade 退出后回到原始页面，能否回到原oaiT的页面
![image](https://github.com/user-attachments/assets/42a388f3-8234-4eaa-a122-41f4dbb3c1c5)

![image](https://github.com/user-attachments/assets/b8e51117-61c3-4981-a4f3-689e22c50af3)

**Comment by Chenyme** [comment]
这个得在域名反代Fuclaude时设置，退出后重定向到OaiT的网址
