### ISSUE TITLE
【错误】黑暗模式字体颜色错误

### ISSUE THREAD

**Issue by mmwong1984** [Chenyme/oaifree-tools#5]
字的颜色没改
![Screenshot_2024-07-17-16-03-24-36_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/4e051613-4aee-4686-a126-11aff374ee80)

**Comment by Chenyme** [comment]
已强制默认模式为light，且禁止切换dark（dark没做未适配）
